### ISSUE TITLE
Can't install CLI

### ISSUE THREAD

**Issue by 40thpower** [foundation/foundation-cli#103]
Foundation CLI will not install, using this:

$ sudo npm install --global foundation-cli

The attempted install took about 20 minutes, with long pauses between activity.

I'm wondering if this package may have a conflict with Angular CLI, which I recently had to uninstall/reinstall.  Would it help to uninstall / reinstall Foundation CLI?  

Here's the code that came up when the install failed:
`
P-Ts-MBP:Email-library MacBookPro$ sudo npm install --global foundation-cli
Password:
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ECONNRESET: request to https://registry.npmjs.org/npm failed, reason: Client network socket disconnected before secure TLS connection was established
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nextgen-events@^1.0.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'terminal-kit'
npm ERR! notarget 
`

**Comment by DanielRuf** [comment]
In general: please do not run these commands with `sudo`.

Please check if you use any proxy for npm and if you can open https://registry.npmjs.org/npm in a browser window.

This is not directly related to foundation-cli.

**Comment by jemckaleman** [comment]
> 
> 
> Foundation CLI will not install, using this:
> 
> $ sudo npm install --global foundation-cli
> 
> The attempted install took about 20 minutes, with long pauses between activity.
> 
> I'm wondering if this package may have a conflict with Angular CLI, which I recently had to uninstall/reinstall. Would it help to uninstall / reinstall Foundation CLI?
> 
> Here's the code that came up when the install failed:
> `P-Ts-MBP:Email-library MacBookPro$ sudo npm install --global foundation-cli Password: npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ECONNRESET: request to https://registry.npmjs.org/npm failed, reason: Client network socket disconnected before secure TLS connection was established npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation. npm ERR! code ETARGET npm ERR! notarget No matching version found for nextgen-events@^1.0.1 npm ERR! notarget In most cases you or one of your dependencies are requesting npm ERR! notarget a package version that doesn't exist. npm ERR! notarget npm ERR! notarget It was specified as a dependency of 'terminal-kit' npm ERR! notarget `

hey men, all that f***ing error its bout node version, check yours and if it's above 11.15.x you should downgrade. then if you run with any other issue run: npm audit, then fix, and --force if its necessary. If you don't know to run such task, try McDonalds. Good luck 👍...

**Comment by maietta** [comment]
> > Foundation CLI will not install, using this:
> > $ sudo npm install --global foundation-cli
> > The attempted install took about 20 minutes, with long pauses between activity.
> > I'm wondering if this package may have a conflict with Angular CLI, which I recently had to uninstall/reinstall. Would it help to uninstall / reinstall Foundation CLI?
> > Here's the code that came up when the install failed:
> > `P-Ts-MBP:Email-library MacBookPro$ sudo npm install --global foundation-cli Password: npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ECONNRESET: request to https://registry.npmjs.org/npm failed, reason: Client network socket disconnected before secure TLS connection was established npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation. npm ERR! code ETARGET npm ERR! notarget No matching version found for nextgen-events@^1.0.1 npm ERR! notarget In most cases you or one of your dependencies are requesting npm ERR! notarget a package version that doesn't exist. npm ERR! notarget npm ERR! notarget It was specified as a dependency of 'terminal-kit' npm ERR! notarget `
> 
> hey men, all that f***ing error its bout node version, check yours and if it's above 11.15.x you should downgrade. then if you run with any other issue run: npm audit, then fix, and --force if its necessary. If you don't know to run such task, try McDonalds. Good luck 👍...

What an asshole you are. I have been a software developer for 22+ something years now and even I have trouble ciphering some of these erroneous messages.  Your browbeating of another users is uncalled for. You should have just kept your mouth shut. Perhaps you will be using a service one day that will be build by this person. Nothing about this error said "Outdated version of NodeJS" etc. Many people don't even use NodeJS on a daily basis. Foundation CLI has been an issue to use for a while. Consider the fact that we have to downgrade Node and NPM just to use Foundation CLI? That's nuts. I am now looking at running a Foundation CLI in a docker container, linked to my images so that I can lock-in the foundation-cli system within a docker container with it's very own nodejs 10.x install. Not an easy task, but do-able. I'm taking sides here. I support anyone who is learning to code. We need as many in this army as we can get.

**Comment by DanielRuf** [comment]
Please relax @maietta =)

Removed the comment from @jemckaleman and locking this conversation for now.

**Comment by DanielRuf** [comment]
Closing as there was no further feedback. Often antivirus solutions can cause this.
