### ISSUE TITLE
Can not run any foundation-cli commands

### ISSUE THREAD

**Issue by AlexMarcoDAngelo** [foundation/foundation-cli#108]
Evry foundation command i try (including -v) generates this error:
C:\Users\angel\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\format.js:624
                base = round( n / ( 1000 ** logDiv3 ) , roundStep[ logMod ] ) ;
                                          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\angel\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\string-kit\lib\string.js:61:2)

This is with latest foundation-cli, node.js very 6.11.4 (with any new ones other big errors don't allow the cli to even install), git, gulp are latest.  Platform is windows 10

**Comment by AlexMarcoDAngelo** [comment]
Update:
After trying Node.js 8.11.4  now foundation-cli work BUT no foundation new can complete due to errors. Same errors happen when I get into the project folder and try npm install. Errors are:

Build started 9/21/2018 3:39:22 PM.
Project "D:\Websites\coffeetest\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "D:\Websites\coffeetest\node_modules\node-sass\build\binding.sln" (1) is building "D:\Websites\coffeetest\node_
modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "D:\Websites\coffeetest\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "D:\Websites\cof
feetest\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
D:\Websites\coffeetest\node_modules\node-sass\build\src\libsass.vcxproj(20,3): error MSB4019: The imported project "D:\
Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the
file exists on disk.
Done Building Project "D:\Websites\coffeetest\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FA
ILED.

Done Building Project "D:\Websites\coffeetest\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets)
-- FAILED.

Done Building Project "D:\Websites\coffeetest\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"D:\Websites\coffeetest\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"D:\Websites\coffeetest\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"D:\Websites\coffeetest\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
  D:\Websites\coffeetest\node_modules\node-sass\build\src\libsass.vcxproj(20,3): error MSB4019: The imported project "D
:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that th
e file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.06
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Websites\coffeetest\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Websites\\coffeetest\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Websites\coffeetest\node_modules\node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN rollback Rolling back yargs@7.1.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\Websites\coffeetest\node_modules\sass-graph\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\angel\AppData\Roaming\npm-cache\_logs\2018-09-21T19_39_27_185Z-debug.log

**Comment by DanielRuf** [comment]
Try to disable any antivirus scanner, run `npm i -g windows-build-tools --production` and try it again.

These are 2 unrelated errors.

**Comment by DanielRuf** [comment]
Closing as there was no further feedback.
