### ISSUE TITLE
i keep getting “-bash: foundation: command not found” when trying to create new email project with zurb foundation

### ISSUE THREAD

**Issue by jasaunthecoder** [foundation/foundation-cli#112]
Im using a mac and also when i check the version of foundation in terminal it does not seem to be installed. I followed the documentation on zurbs website for email framework install to every step here https://foundation.zurb.com/emails/docs/sass-guide.html, I've googled this and surprisingly no one has had this issue it seems, so im posting for some help. Using the terminal and installing in the terminal is new for me so maybe its something im not doing but ive checked youtube tutorials on this and docs online and i seem to be doing it the right way, any help would be appreciated.

**Comment by DanielRuf** [comment]
Hi @jasaunthecoder,

did you run `npm install --global foundation-cli`?
What did this output to your terminal?

**Comment by jasaunthecoder** [comment]
Users-MBP:~ jasaunknight$ npm install --global foundation-cli
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN checkPermissions Missing write access to /Users/jasaunknight/.npm-global/lib/node_modules/foundation-cli
npm ERR! path /Users/jasaunknight/.npm-global/lib/node_modules/foundation-cli
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/jasaunknight/.npm-global/lib/node_modules/foundation-cli'
npm ERR!  [Error: EACCES: permission denied, access '/Users/jasaunknight/.npm-global/lib/node_modules/foundation-cli'] {
npm ERR!   stack: 'Error: EACCES: permission denied, access ' +
npm ERR!     "'/Users/jasaunknight/.npm-global/lib/node_modules/foundation-cli'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/jasaunknight/.npm-global/lib/node_modules/foundation-cli'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jasaunknight/.npm/_logs/2019-06-10T00_25_43_567Z-debug.log

**Comment by DanielRuf** [comment]
This probably means that you have once unstalled npm with `sudo` which will break things (never use `sudo`). You can fix the rights / owner with `chown`.

**Comment by jasaunthecoder** [comment]
Forgive me Daniel but i'm new to terminal installations. How exactly would i do that with chown in steps please. And thanks for actually responding to me. And do you have any recommendations for guides, or tutorials on how i can understand the terminal, installations and paths because there are things im missing and if i plan on being a developer i want to know as much as i can.

**Comment by JHunnicutt** [comment]
Daniel, Should users be warned about this feature from Zurb's website? This is one of the instruction's given. 

I located my foundation cli and found that it is owned by the root user. I attempted to change it and was told the operation was not permitted.

Jasaun, find more about the chown command here, https://linuxize.com/post/linux-chown-command/.

**Comment by DanielRuf** [comment]
Learning everything about terminals and the commands is quite much. There are many tutorials but I can not recommend a specific one in general.

For changing the owner you might hae to use `sudo` when it is owned by root.
`sudo chown -R $USER: {} +`

This will change the owner of the current directory and all files and directories in it to the current user.

**Comment by DanielRuf** [comment]
> Daniel, Should users be warned about this feature from Zurb's website?

I can not update the marketing website and docs as this is hosted on the servers of ZURB and without any access to them (SSH keys) I can not do much.

**Comment by JHunnicutt** [comment]
I totally understand. I assume you are just a good soul who knows a lot about the Foundation cli

**Comment by jasaunthecoder** [comment]
so i wound up fixing permission errors by using the su terminal command and that gave me root access for the time and allowed me to install and foundation is now working(thankfully). I permanently gave myself permanent root access by following these instructions here http://www.macinstruct.com/node/389.
Im glad these happened because i can use the terminal better and understand its functionality a bit better. thanks daniel, and jhunnicutt hopefully those root access instructions help you out. Ask me anything if you need further detail into how to do it.

**Comment by DanielRuf** [comment]
Closing as resolved. Thanks for the feedback.
