### ISSUE TITLE
har-validator Not Found error

### ISSUE THREAD

**Issue by kevinmu17** [foundation/foundation-cli#115]
After cli command 'foundation new' it has a missing file in the package-lock.json.
```
Not Found - GET https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
npm ERR! 404 
npm ERR! 404  'har-validator@5.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'PROJECTNAME'
```

**To reproduce it follow steps**
```
foundation new
```
after completion
```
npm install
```

**Temp solution:**
1. delete package-lock.json & node_modules folder
2. run npm install again

I have no clue what this package does so before i'll do anything further with pull requests i need a little information on this one.

**Comment by DanielRuf** [comment]
Hi @kevinmu17,

The author and maintainer unpublished it. Please delete the lockfile and try it again.

**Comment by DanielRuf** [comment]
Therevis no PR needed, we will update the lockfiles then.

**Comment by DanielRuf** [comment]
Should be resolved by now.
