### ISSUE TITLE
Foundation-cli install error

### ISSUE THREAD

**Issue by troylinker** [foundation/foundation-cli#116]
I am installing foundation-cli to experiment, work the tutorials and learn the ZURB stack. I have basic programming and node js skills. I receive the following error when trying to run my first cli command. 

The cli appears to install properly with two warnings.

>`Troys-iMac:~ troylinker$ npm install --global foundation-cli
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/Users/troylinker/.nvm/versions/node/v12.11.0/bin/foundation -> /Users/troylinker/.nvm/versions/node/v12.11.0/lib/node_modules/foundation-cli/bin/foundation.js
//+ foundation-cli@2.2.5
added 324 packages from 531 contributors in 8.063s`

but when I run my first `foundation new --framework emails` command I get the following error

>`Troys-iMac:~ troylinker$ foundation new --framework emails
fs.js:27
const { Math, Object } = primordials;
                         ^
>.ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/troylinker/.nvm/versions/node/v12.11.0/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/troylinker/.nvm/versions/node/v12.11.0/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/troylinker/.nvm/versions/node/v12.11.0/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)`

It appears to be related to natives, but I am not sure about the best next steps to take to solve the issue. I don't want to get sucked into a rabbit hole of trial and error if someone else has a quick solution. Any help in troubleshooting is greatly appreciated. 

**My enviornment**
iMac - Catalina v10.15.
nvm v0.34.0 
node v12.11.0

**Comment by DanielRuf** [comment]
Hi, please downgrade / switch to NodeJS 10.

**Comment by DanielRuf** [comment]
Hib@troylinker, please downgrade / switch to NodeJS 10.

**Comment by DanielRuf** [comment]
Hi @troylinker, please downgrade / switch to NodeJS 10.

**Comment by troylinker** [comment]
Great, thanks I downgraded to node v10.16.3. Now after running `foundation new --framework emails`

I get the following:

>? What's the project called? (no spaces) nwibiz_newsletter_test

>Downloading the project template...
Done downloading!

>Installing dependencies...

>npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
\
There were some problems during the installation.

> ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.

>Once you've resolved the above issues, run foundation watch while inside the nwibiz_newsletter_test folder.

Can you help me troubleshoot the syntax error and where to fix it in the package.json, gulpfile.babel.js or where ever the problem resides?

**Comment by troylinker** [comment]
Ok I changed
 >"gulp": "git+https://github.com/gulpjs/gulp.git#4.0",

to 
>"gulp": "^4.0.0",

in the package.json

I did an npm install and an npm run. Your welcome screen opened on my localhost. I haven't tried anything else, but it looks like it is installed and running now.  Thanks for your help!

**Comment by DanielRuf** [comment]
Awesome =)

I think you can close issue now. We have already many reports of the gulp issue and a solution.

**Comment by Hideman85** [comment]
Have same issue can we have a workaround for node v12?

**Comment by DanielRuf** [comment]
> Have same issue can we have a workaround for node v12?

This is an issue with the dependencies and lockfile. It does not happen on the develop branch.

**Comment by Hideman85** [comment]
Can it be deployed to npm repos?

**Comment by DanielRuf** [comment]
Currently not. We are preparing v6.6. We do not yet have a ETA.

You can use nvm, nodenv, n or nvs to switch to NodeJS 10.

**Comment by DanielRuf** [comment]
Also please open a new issue with more details so we can take care of that.

**Comment by Hideman85** [comment]
Alternative:
- Clone this project: https://github.com/foundation/foundation-emails-template
- Update dependencies to avoid issue on installation (node-sass compilation not work) `npx npm-check-updates -u`
- Run `npm i`
- And finally `npm start` work
