### ISSUE TITLE
Installation of Foundation-CLI on QNAP resolves "foundation: command not found"

### ISSUE THREAD

**Issue by Encuen** [foundation/foundation-cli#128]
Trying to install Foundation on a QNAP via SSH. Logged as admin.
I am an absolute noob on console (Windows user). After reading guides and online instructions, I do this:

**Install gulp and bower**
[/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin] # npm install -g gulp bower
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin/bower -> /share/CACHEDEV1_DATA/.qpkg/NodeJS/lib/node_modules/bower/bin/bower
/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin/gulp -> /share/CACHEDEV1_DATA/.qpkg/NodeJS/lib/node_modules/gulp/bin/gulp.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/gulp/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ gulp@4.0.2
+ bower@1.8.8
added 317 packages from 218 contributors in 7.19s

**Then FOUNDATION-CLI**
npm install --global foundation-cli
[/share/CACHEDEV1_DATA/.qpkg/NodeJS] # npm install --global foundation-cli
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin/foundation -> /share/CACHEDEV1_DATA/.qpkg/NodeJS/lib/node_modules/foundation-cli/bin/foundation.js
+ foundation-cli@2.2.5
added 329 packages from 534 contributors in 8.916s

**Then Run FOUNDATION and GET THE ERROR**
[/share/CACHEDEV1_DATA/.qpkg/NodeJS] # foundation
-sh: foundation: command not found

What am I doing wrong?

Thank you so much.

**Comment by Encuen** [comment]
I think I did something wrong (sorry about my low level with Linux console).

[admin@WALL-e node_modules]# npm install --global foundation-cli
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin/foundation -> /share/CACHEDEV1_DATA/.qpkg/NodeJS/lib/node_modules/foundation-cli/bin/foundation.js
+ foundation-cli@2.2.5
added 329 packages from 534 contributors in 6.86s
[admin@WALL-e node_modules]# foundation
bash: foundation: command not found
[admin@WALL-e node_modules]# source ~/.bashrc
[admin@WALL-e node_modules]# bash
[admin@WALL-e node_modules]# npm bin -g
/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin
(not in PATH env variable)
[admin@WALL-e node_modules]# foundation
bash: foundation: command not found
[admin@WALL-e node_modules]#

Thank you in advance for the blazing fast help.

**Comment by DanielRuf** [comment]
>     * /share/CACHEDEV1_DATA/.qpkg/NodeJS/bin
>       (not in PATH env variable)

You have to export the PATH with this appended to it, alternatively run `/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin/foundation`

**Comment by DanielRuf** [comment]
>     * /share/CACHEDEV1_DATA/.qpkg/NodeJS/bin
>       (not in PATH env variable)

You have to export the PATH with this prepended to it, alternatively run `/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin/foundation`.

If you want to append it to the PATH variable, open `~/.bashrc` and add `export PATH="/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin:$PATH`

**Comment by DanielRuf** [comment]
>     * /share/CACHEDEV1_DATA/.qpkg/NodeJS/bin
>       (not in PATH env variable)

You have to export the PATH with this prepended to it, alternatively run `/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin/foundation`.

If you want to prepend it to the PATH variable, open `~/.bashrc` and add `export PATH="/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin:$PATH`, then run the `source`command again, output it with `echo $PATH` and try it again.

**Comment by Encuen** [comment]
First step done, i think

[admin@WALL-e ~]# echo $PATH
/share/CACHEDEV1_DATA/.qpkg/NodeJS/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/bin/X11:/usr/local/bin
[admin@WALL-e ~]# foundation
fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (/share/CACHEDEV1_DATA/.qpkg/NodeJS/lib/node_modules/foundation-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/share/CACHEDEV1_DATA/.qpkg/NodeJS/lib/node_modules/foundation-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/share/CACHEDEV1_DATA/.qpkg/NodeJS/lib/node_modules/foundation-cli/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
[admin@WALL-e ~]#

**Comment by DanielRuf** [comment]
That is correct. Now you have to downgrade to Node 10 or 8 as the gulp version uses a dependency that does not support Node 12 and newer.

**Comment by DanielRuf** [comment]
For this you can use nvm, nodenv or n (last one is probably easiest).

**Comment by Encuen** [comment]
Thank you so much. It worked like a charm!! The 'n' command is absurdly efficient.
Let's code!
