### ISSUE TITLE
Package-lock.json contains every NPM library there is on fresh install

### ISSUE THREAD

**Issue by kevinmu17** [foundation/foundation-cli#134]
After `foundation new`, when doing `npm install` it installs every NPM library existing into the node_modules folder... This can't be right. When removing package-lock.json hell breaks lose. Anyone else having this issue?

FYI: in the past I used `npm set legacy-bundling=true` to prevent this behaviour

**Comment by DanielRuf** [comment]
I don' quite understand what you mean.
This sounds more like an issue with your npm version.
I've never needed `npm set legacy-bundling=true`, npm installs what is in package.json and nothing more (plus all the dependencies of the dependencies).

**Comment by kevinmu17** [comment]
> npm installs what is in package.json and nothing more
Thats what I expect it to do, but somehow it installs everything from NPM, unless i delete the package-lock file, where all these libraries do exist... so there is something weird going on here.

I've updated my NPM to version 6.14.8, after it the problem still exists so i don't think it's my NPM

**Comment by DanielRuf** [comment]
I still don't know what exactly you mean. It is normal that all the packages in the lockfile are downloaded. And it is normal that these are many.

**Comment by DanielRuf** [comment]
Please provide some reproducible example, screenshots and logfiles.

**Comment by kevinmu17** [comment]
No, thats the problem. I'll try to clarify by steps.

1. foundation new > website > zurb template
It downloads everything needed, here is the node_modules folder (AS It SHOULD LOOK LIKE)
![Screen Shot 2020-09-29 at 18 28 06](https://user-images.githubusercontent.com/8747373/94586754-e9b63000-0281-11eb-99a6-6b0e5621598d.png)
2. testing `foundation watch`, works still as expected.
3. Now, install any random library or just do a `npm install` for this case.
Now the node_modules folder is totally bulked up with every library from NPM, which should not happen because they are bloating my system and are not needed in any way for the project. (can't fit it into the screenshot, but you will get the idea from the alphabetic order)
![Screen Shot 2020-09-29 at 18 37 33](https://user-images.githubusercontent.com/8747373/94587428-de173900-0282-11eb-979a-7f314946a1f4.png)

Now, if I delete the package-lock.json before step 3, it installs the needed node_modules fine and updates the foundation-sites too (which is the endgame in my case, foundation new is starting with foundation-sites 6.5.1 ?!) but this should not be in my workflow right? :)

**Comment by DanielRuf** [comment]
The behavior is correct, this is not every package from npmjs, just newer dependencies and sub-dependencies.

`npm ci` installs from the lockfile, `npm i` does not and updates packages according to the SemVer ranges in package.json.

**Comment by DanielRuf** [comment]
Your legacy install config is probably the cause as this may use the pre npm 5 flat folder structure, not the nested one like we normally have (node_modules then contains the packages from package.json on the first level).

**Comment by DanielRuf** [comment]
See https://stackoverflow.com/a/35227212/753676

![Uploading Bildschirmfoto 2020-09-29 um 20.43.11.png…]()

**Comment by DanielRuf** [comment]
See https://stackoverflow.com/a/35227212/753676

<img width="661" alt="Bildschirmfoto 2020-09-29 um 20 43 11" src="https://user-images.githubusercontent.com/827205/94601973-8c77aa00-0294-11eb-8a12-e166deaa3a69.png">

I'm not sure (I searched and found no further information) but the state with the more folders is the latest and current behavior.

So in my opinion nothing is wrong here.

**Comment by kevinmu17** [comment]
Okay, I searched the node_modules for sub-dependencies and it seems to be legit, but quick followup question, is it my system or the `foundation new` command that is causing the "nicer compact" overview? Shouldn't `foundation new` create a node_modules folder like my second screenshot?

FYI: my NPM version is 6.14.8 and it's still doing the legacy-bundling (I suppose, after debugging this after step 3) so the dropped support is incorrect i think, they still mention this in newer versions: https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson

**Comment by DanielRuf** [comment]
> Okay, I searched the node_modules for sub-dependencies and it seems to be legit, but quick followup question, is it my system or the `foundation new` command that is causing the "nicer compact" overview? Shouldn't `foundation new` create a node_modules folder like my second screenshot?

It's "caused" by npm which is used by foundation. There is nothing special that `foundation new` does, only a `git clone` and `npm i`.

**Comment by kevinmu17** [comment]
Okay! thanks for the help Daniel! this clarified a lot for me, This also brings done my node modules folder from +/- 450mb to +/- 130mb diskspace! Topic closed
