### ISSUE TITLE
Lock NPM Colors.js package version

### ISSUE THREAD

**Issue by pfasang** [foundation/foundation-cli#149]
Hi everyone, please lock the version of `colors.js` package ASAP. 

Here is thread, related to this issue: https://github.com/Marak/colors.js/issues/290

**Comment by lukeoregan88** [comment]
I second this motion! There must be an override for this? Trying to use Foundation for Emails but I can't do anything!

`https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected`

**Comment by lukeoregan88** [comment]
I've created a pull request.

`https://github.com/foundation/foundation-cli/pull/150` let's see if they do anything.

**Comment by lukeoregan88** [comment]
@joeworkman can you confirm if that works? I've updated and ran foundation -v and I'm still having the same issue with the 'LIBERTY' message and colors.js. 

Still can't seem to install anything through the CLI? I've checked and I am running the latest version at 2.3.2.

FYI i'm running node 16 --lts using NVM

**Comment by joeworkman** [comment]
You may need to reinstall the packages via npm or yarn. You may have a more recent version than v1.4.0 of colors

**Comment by joeworkman** [comment]
I just tested and I am getting colors v1.4.0 when I install a clean version.

**Comment by lukeoregan88** [comment]
@joeworkman reinstall of packages via npm did the trick. Thank you very much for the support and applying a fix.
